// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpeedInfo struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Number               string               `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Speed                float32              `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SpeedInfo) Reset()         { *m = SpeedInfo{} }
func (m *SpeedInfo) String() string { return proto.CompactTextString(m) }
func (*SpeedInfo) ProtoMessage()    {}
func (*SpeedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *SpeedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpeedInfo.Unmarshal(m, b)
}
func (m *SpeedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpeedInfo.Marshal(b, m, deterministic)
}
func (m *SpeedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpeedInfo.Merge(m, src)
}
func (m *SpeedInfo) XXX_Size() int {
	return xxx_messageInfo_SpeedInfo.Size(m)
}
func (m *SpeedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SpeedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SpeedInfo proto.InternalMessageInfo

func (m *SpeedInfo) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *SpeedInfo) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *SpeedInfo) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func init() {
	proto.RegisterType((*SpeedInfo)(nil), "api.SpeedInfo")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0x92,
	0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x25, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6,
	0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x54, 0x29, 0x65, 0x72, 0x71, 0x06, 0x17, 0xa4, 0xa6,
	0xa6, 0x78, 0xe6, 0xa5, 0xe5, 0x0b, 0xe9, 0x71, 0xb1, 0xa4, 0x24, 0x96, 0xa4, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x1b, 0x49, 0xe9, 0x41, 0x34, 0xeb, 0xc1, 0x34, 0xeb, 0x85, 0xc0, 0x34, 0x07,
	0x81, 0xd5, 0x09, 0x89, 0x71, 0xb1, 0xe5, 0x95, 0xe6, 0x26, 0xa5, 0x16, 0x49, 0x30, 0x29, 0x30,
	0x6a, 0x70, 0x06, 0x41, 0x79, 0x42, 0x22, 0x5c, 0xac, 0xc5, 0x20, 0x43, 0x25, 0x98, 0x15, 0x18,
	0x35, 0x98, 0x82, 0x20, 0x9c, 0x24, 0x36, 0xb0, 0x39, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x16, 0x1f, 0x42, 0xe2, 0xa8, 0x00, 0x00, 0x00,
}
